version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-color
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - mongo_hydromnis
  server:
    build: ./server
    container_name: server-color
    restart: always
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=api-hydromnis.lafuentedanel.com
      - LETSENCRYPT_HOST=api-hydromnis.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - proxy
      - mongo_hydromnis

  client:
    image: nginx
    container_name: client-color
    restart: always
    depends_on:
      - server
    environment:
      - VIRTUAL_HOST=hydromnis.lafuentedanel.com
      - LETSENCRYPT_HOST=hydromnis.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
        - proxy


networks:
  proxy:
    name: nginx-proxy
    external: true
  mongo_hydromnis:
    name: mongo_hydromnis
    external: false
