version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-color
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - proxy
      - mongo_hydromnis
  server:
    build: ./server
    container_name: server-color
    restart: always
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=api-hydromnis.lafuentedanel.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api-hydromnis.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - proxy
      - mongo_hydromnis

networks:
  proxy:
    name: nginx-proxy
    external: true
  mongo_hydromnis:
    name: mongo_hydromnis
    external: false
