version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-color
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  server:
    build: ./server
    container_name: server-color
    restart: always
    ports:
      - 3999:3000
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

